# Generated by Django 4.1.3 on 2023-01-22 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CONCERTS', 'Concerts'), ('SPORTS', 'Sports'), ('ARTS_THEATER', 'Arts & Theater')], default='CONCERTS', max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
            ],
        ),
    ]
