# Generated by Django 4.1.5 on 2023-01-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='event',
        ),
        migrations.AddField(
            model_name='events',
            name='reviews',
            field=models.ManyToManyField(to='main_app.review'),
        ),
    ]
