# Generated by Django 4.1.5 on 2023-01-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_review_event_events_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='reviews',
        ),
    ]
