# Generated by Django 4.1.3 on 2023-01-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_review_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_events',
            field=models.ManyToManyField(blank=True, to='main_app.events'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
