# Generated by Django 4.1.3 on 2023-01-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_events_description'),
    ]

    operations = [
    ]
