# Generated by Django 4.1.3 on 2023-01-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20230122_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='description',
        ),
    ]
