# Generated by Django 4.1.3 on 2023-01-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_events_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
