# Generated by Django 4.1.5 on 2023-01-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_events_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
